import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        description: 'Comprehensive list of Slint UI components included in the kit.',
      },
      items: [
        {
          type: 'category',
          label: 'Buttons',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/buttons'
            }
          ]
        },
        {
          type: 'category',
          label: 'Inputs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/inputs'
            }
          ]
        },
        {
          type: 'category',
          label: 'Knobs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/knobs'
            }
          ]
        },
        {
          type: 'category',
          label: 'Labels',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/labels'
            }
          ]
        },
        {
          type: 'category',
          label: 'Selectors',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/selectors'
            }
          ]
        },
        {
          type: 'category',
          label: 'Sliders',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/sliders'
            }
          ]
        },
        {
          type: 'category',
          label: 'Toggles',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/toggles'
            }
          ]
        },
        {
          type: 'category',
          label: 'Visualizers',
          items: [
            {
              type: 'autogenerated',
              dirName: 'components/viz'
            }
          ]
        }
      ],
    },
    'theming',
    'demo',
    'onboarding',
    'changelog',
    'license'
  ]
};

export default sidebars;
