import { Theme } from "../theme/index.slint";

export component RDSHeaderLabel {
    in property <string> text;
    in property <TextVerticalAlignment> vertical-alignment: center;
    in property <TextHorizontalAlignment> horizontal-alignment: center;
    in property <length> padding-horizontal: 8px;
    in property <length> padding-vertical: 4px;
    in property <length> right-padding: 8px;
    in property <length> right-gap: 6px;
    in property <length> border-r-tl: Theme.active.radius_large;
    in property <length> border-r-tr: Theme.active.radius_large;
    in property <length> border-r-bl: Theme.active.radius_large;
    in property <length> border-r-br: Theme.active.radius_large;
    in property <length> letter-spacing: 1px;
    in property <color> bg-color: Theme.active.ui-header-label-bg;
    in property <color> txt-color: Theme.active.text-primary;
    height: 30px;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: root.bg-color;
        border-top-left-radius: root.border-r-tl;
        border-top-right-radius: root.border-r-tr;
        border-bottom-left-radius: root.border-r-bl;
        border-bottom-right-radius: root.border-r-br;
        Text {
            x: root.padding-horizontal;
            y: root.padding-vertical;
            width: Math.max(0px, parent.width - (root.padding-horizontal * 2));
            height: Math.max(0px, parent.height - (root.padding-vertical * 2));
            text: root.text;
            color: root.txt-color;
            font-family: Theme.active.font_body;
            font-size: Theme.active.font_large;
            horizontal-alignment: root.horizontal-alignment;
            vertical-alignment: root.vertical-alignment;
            letter-spacing: root.letter-spacing;
        }
        right-slot := HorizontalLayout {
            y: root.padding-vertical;
            height: Math.max(0px, parent.height - (root.padding-vertical * 2));
            width: self.preferred-width;
            x: parent.width - self.width - root.right-padding;
            alignment: center;
            spacing: root.right-gap;
            @children
        }
    }
}
